// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Player.proto

package protobuf.player;

public interface PlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Player)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint64 enterTime = 3;</code>
   * @return The enterTime.
   */
  long getEnterTime();
}
