// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Player.proto

package logic.player;

public final class PlayerOuterClass {
  private PlayerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_Player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Player.proto\022\004user\"5\n\006Player\022\n\n\002id\030\001 \001" +
      "(\r\022\014\n\004name\030\002 \001(\t\022\021\n\tenterTime\030\003 \001(\004B\023\n\017p" +
      "rotobuf.playerP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_Player_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_Player_descriptor,
        new java.lang.String[] { "Id", "Name", "EnterTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
