// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package logic.protocol;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_HeartBeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_HeartBeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Protocol.proto\022\004user\"5\n\006Player\022\n\n\002id\030\001" +
      " \001(\r\022\014\n\004name\030\002 \001(\t\022\021\n\tenterTime\030\003 \001(\004\"$\n" +
      "\tHeartBeat\022\027\n\017system_currtime\030\001 \001(\003B\034\n\016l" +
      "ogic.protocolB\010ProtocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_Player_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_Player_descriptor,
        new java.lang.String[] { "Id", "Name", "EnterTime", });
    internal_static_user_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_HeartBeat_descriptor,
        new java.lang.String[] { "SystemCurrtime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
