// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package logic.protocol;

public interface HBInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.HBInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 system_currtime = 1;</code>
   * @return The systemCurrtime.
   */
  long getSystemCurrtime();
}
