// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package logic.protocol;

public interface HeartBeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.HeartBeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *服务器当前时间
   * </pre>
   *
   * <code>int64 system_currtime = 1;</code>
   * @return The systemCurrtime.
   */
  long getSystemCurrtime();
}
