// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package logic.protocol;

public interface MotionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.MotionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 1;</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>float x = 2;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 3;</code>
   * @return The y.
   */
  float getY();
}
