// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package logic.protocol;

public interface MotionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Motion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 uid = 1;</code>
   * @return The uid.
   */
  int getUid();

  /**
   * <code>float x = 2;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 3;</code>
   * @return The y.
   */
  float getY();
}
