// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package logic.protocol;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_UserList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_UserList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_LoginInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_LoginInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_HBInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_HBInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_MotionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_MotionInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Protocol.proto\022\010protocol\"5\n\006Player\022\n\n\002" +
      "id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\021\n\tenterTime\030\003 \001(" +
      "\004\".\n\010UserList\022\"\n\010userList\030\001 \003(\0132\020.protoc" +
      "ol.Player\"7\n\tLoginInfo\022\n\n\002id\030\001 \001(\t\022\013\n\003pw" +
      "d\030\002 \001(\t\022\021\n\tenterTime\030\003 \001(\004\"!\n\006HBInfo\022\027\n\017" +
      "system_currtime\030\001 \001(\003\"/\n\nMotionInfo\022\013\n\003u" +
      "id\030\001 \001(\t\022\t\n\001x\030\002 \001(\002\022\t\n\001y\030\003 \001(\002B\034\n\016logic." +
      "protocolB\010ProtocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_Player_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Player_descriptor,
        new java.lang.String[] { "Id", "Name", "EnterTime", });
    internal_static_protocol_UserList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_UserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_UserList_descriptor,
        new java.lang.String[] { "UserList", });
    internal_static_protocol_LoginInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_LoginInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_LoginInfo_descriptor,
        new java.lang.String[] { "Id", "Pwd", "EnterTime", });
    internal_static_protocol_HBInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protocol_HBInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_HBInfo_descriptor,
        new java.lang.String[] { "SystemCurrtime", });
    internal_static_protocol_MotionInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protocol_MotionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_MotionInfo_descriptor,
        new java.lang.String[] { "Uid", "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
