// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package logic.protocol;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  java.util.List<logic.protocol.Player> 
      getUserListList();
  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  logic.protocol.Player getUserList(int index);
  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  int getUserListCount();
  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  java.util.List<? extends logic.protocol.PlayerOrBuilder> 
      getUserListOrBuilderList();
  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  logic.protocol.PlayerOrBuilder getUserListOrBuilder(
      int index);
}
