// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package logic.protocol;

/**
 * Protobuf type {@code protocol.UserList}
 */
public final class UserList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.UserList)
    UserListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserList.newBuilder() to construct.
  private UserList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserList() {
    userList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              userList_ = new java.util.ArrayList<logic.protocol.Player>();
              mutable_bitField0_ |= 0x00000001;
            }
            userList_.add(
                input.readMessage(logic.protocol.Player.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        userList_ = java.util.Collections.unmodifiableList(userList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return logic.protocol.Protocol.internal_static_protocol_UserList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return logic.protocol.Protocol.internal_static_protocol_UserList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            logic.protocol.UserList.class, logic.protocol.UserList.Builder.class);
  }

  public static final int USERLIST_FIELD_NUMBER = 1;
  private java.util.List<logic.protocol.Player> userList_;
  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<logic.protocol.Player> getUserListList() {
    return userList_;
  }
  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends logic.protocol.PlayerOrBuilder> 
      getUserListOrBuilderList() {
    return userList_;
  }
  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  @java.lang.Override
  public int getUserListCount() {
    return userList_.size();
  }
  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  @java.lang.Override
  public logic.protocol.Player getUserList(int index) {
    return userList_.get(index);
  }
  /**
   * <code>repeated .protocol.Player userList = 1;</code>
   */
  @java.lang.Override
  public logic.protocol.PlayerOrBuilder getUserListOrBuilder(
      int index) {
    return userList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < userList_.size(); i++) {
      output.writeMessage(1, userList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < userList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, userList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof logic.protocol.UserList)) {
      return super.equals(obj);
    }
    logic.protocol.UserList other = (logic.protocol.UserList) obj;

    if (!getUserListList()
        .equals(other.getUserListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserListCount() > 0) {
      hash = (37 * hash) + USERLIST_FIELD_NUMBER;
      hash = (53 * hash) + getUserListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static logic.protocol.UserList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static logic.protocol.UserList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static logic.protocol.UserList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static logic.protocol.UserList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static logic.protocol.UserList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static logic.protocol.UserList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static logic.protocol.UserList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static logic.protocol.UserList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static logic.protocol.UserList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static logic.protocol.UserList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static logic.protocol.UserList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static logic.protocol.UserList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(logic.protocol.UserList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.UserList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.UserList)
      logic.protocol.UserListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return logic.protocol.Protocol.internal_static_protocol_UserList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return logic.protocol.Protocol.internal_static_protocol_UserList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              logic.protocol.UserList.class, logic.protocol.UserList.Builder.class);
    }

    // Construct using logic.protocol.UserList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUserListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userListBuilder_ == null) {
        userList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        userListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return logic.protocol.Protocol.internal_static_protocol_UserList_descriptor;
    }

    @java.lang.Override
    public logic.protocol.UserList getDefaultInstanceForType() {
      return logic.protocol.UserList.getDefaultInstance();
    }

    @java.lang.Override
    public logic.protocol.UserList build() {
      logic.protocol.UserList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public logic.protocol.UserList buildPartial() {
      logic.protocol.UserList result = new logic.protocol.UserList(this);
      int from_bitField0_ = bitField0_;
      if (userListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          userList_ = java.util.Collections.unmodifiableList(userList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userList_ = userList_;
      } else {
        result.userList_ = userListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof logic.protocol.UserList) {
        return mergeFrom((logic.protocol.UserList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(logic.protocol.UserList other) {
      if (other == logic.protocol.UserList.getDefaultInstance()) return this;
      if (userListBuilder_ == null) {
        if (!other.userList_.isEmpty()) {
          if (userList_.isEmpty()) {
            userList_ = other.userList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserListIsMutable();
            userList_.addAll(other.userList_);
          }
          onChanged();
        }
      } else {
        if (!other.userList_.isEmpty()) {
          if (userListBuilder_.isEmpty()) {
            userListBuilder_.dispose();
            userListBuilder_ = null;
            userList_ = other.userList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            userListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUserListFieldBuilder() : null;
          } else {
            userListBuilder_.addAllMessages(other.userList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      logic.protocol.UserList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (logic.protocol.UserList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<logic.protocol.Player> userList_ =
      java.util.Collections.emptyList();
    private void ensureUserListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        userList_ = new java.util.ArrayList<logic.protocol.Player>(userList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        logic.protocol.Player, logic.protocol.Player.Builder, logic.protocol.PlayerOrBuilder> userListBuilder_;

    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public java.util.List<logic.protocol.Player> getUserListList() {
      if (userListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userList_);
      } else {
        return userListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public int getUserListCount() {
      if (userListBuilder_ == null) {
        return userList_.size();
      } else {
        return userListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public logic.protocol.Player getUserList(int index) {
      if (userListBuilder_ == null) {
        return userList_.get(index);
      } else {
        return userListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public Builder setUserList(
        int index, logic.protocol.Player value) {
      if (userListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserListIsMutable();
        userList_.set(index, value);
        onChanged();
      } else {
        userListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public Builder setUserList(
        int index, logic.protocol.Player.Builder builderForValue) {
      if (userListBuilder_ == null) {
        ensureUserListIsMutable();
        userList_.set(index, builderForValue.build());
        onChanged();
      } else {
        userListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public Builder addUserList(logic.protocol.Player value) {
      if (userListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserListIsMutable();
        userList_.add(value);
        onChanged();
      } else {
        userListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public Builder addUserList(
        int index, logic.protocol.Player value) {
      if (userListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserListIsMutable();
        userList_.add(index, value);
        onChanged();
      } else {
        userListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public Builder addUserList(
        logic.protocol.Player.Builder builderForValue) {
      if (userListBuilder_ == null) {
        ensureUserListIsMutable();
        userList_.add(builderForValue.build());
        onChanged();
      } else {
        userListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public Builder addUserList(
        int index, logic.protocol.Player.Builder builderForValue) {
      if (userListBuilder_ == null) {
        ensureUserListIsMutable();
        userList_.add(index, builderForValue.build());
        onChanged();
      } else {
        userListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public Builder addAllUserList(
        java.lang.Iterable<? extends logic.protocol.Player> values) {
      if (userListBuilder_ == null) {
        ensureUserListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userList_);
        onChanged();
      } else {
        userListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public Builder clearUserList() {
      if (userListBuilder_ == null) {
        userList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        userListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public Builder removeUserList(int index) {
      if (userListBuilder_ == null) {
        ensureUserListIsMutable();
        userList_.remove(index);
        onChanged();
      } else {
        userListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public logic.protocol.Player.Builder getUserListBuilder(
        int index) {
      return getUserListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public logic.protocol.PlayerOrBuilder getUserListOrBuilder(
        int index) {
      if (userListBuilder_ == null) {
        return userList_.get(index);  } else {
        return userListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public java.util.List<? extends logic.protocol.PlayerOrBuilder> 
         getUserListOrBuilderList() {
      if (userListBuilder_ != null) {
        return userListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userList_);
      }
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public logic.protocol.Player.Builder addUserListBuilder() {
      return getUserListFieldBuilder().addBuilder(
          logic.protocol.Player.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public logic.protocol.Player.Builder addUserListBuilder(
        int index) {
      return getUserListFieldBuilder().addBuilder(
          index, logic.protocol.Player.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.Player userList = 1;</code>
     */
    public java.util.List<logic.protocol.Player.Builder> 
         getUserListBuilderList() {
      return getUserListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        logic.protocol.Player, logic.protocol.Player.Builder, logic.protocol.PlayerOrBuilder> 
        getUserListFieldBuilder() {
      if (userListBuilder_ == null) {
        userListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            logic.protocol.Player, logic.protocol.Player.Builder, logic.protocol.PlayerOrBuilder>(
                userList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        userList_ = null;
      }
      return userListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.UserList)
  }

  // @@protoc_insertion_point(class_scope:protocol.UserList)
  private static final logic.protocol.UserList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new logic.protocol.UserList();
  }

  public static logic.protocol.UserList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserList>
      PARSER = new com.google.protobuf.AbstractParser<UserList>() {
    @java.lang.Override
    public UserList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public logic.protocol.UserList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

